import { FileText, Download, Printer, Award, ChevronDown, ChevronUp, Loader2 } from 'lucide-react';
import { useAsync } from '../../../lib/useAsync.js';
import { useRecordEvents } from '../../../lib/useRecordEvents.js';
import { useAuth } from '../../auth/hooks/useAuth.js';
import { extractErrorMessage } from '../../auth/api/auth.api.js';
import { getTranscriptRequest } from '../api/student.api.js';
import { Badge } from '../../../components/ui/Badge.jsx';
import { EmptyState } from '../../../components/ui/EmptyState.jsx';
import { ErrorState } from '../../../components/ui/ErrorState.jsx';
import { PageHeader } from '../../../components/ui/PageHeader.jsx';
import { Spinner } from '../../../components/ui/Spinner.jsx';
import { Button } from '../../../components/ui/Button.jsx';

function percentage(obtained, max) {
  if (!max) return null;
  return Math.round((obtained / max) * 100);
}

function GradeBadge({ grade, source }) {
  const tones = { 9: 'slate', 10: 'blue', 11: 'purple', 12: 'primary' };
  return (
    <Badge tone={tones[grade] || 'neutral'} className="gap-1">
      Grade {grade}
      {source === 'historical' && <span className="ml-1 px-1.5 py-0.5 text-[10px] rounded bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300">Historical</span>}
      {source === 'system' && <span className="ml-1 px-1.5 py-0.5 text-[10px] rounded bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300">Current</span>}
    </Badge>
  );
}

function printTranscript() {
  window.print();
}

function downloadTranscript(student, transcript) {
  const lines = [];
  lines.push('OFFICIAL TRANSCRIPT');
  lines.push('='.repeat(50));
  lines.push('');
  lines.push(`Student: ${student.name}`);
  lines.push(`National ID: ${student.nationalId || 'N/A'}`);
  lines.push(`Roll Number: ${student.rollNumber || 'N/A'}`);
  lines.push(`Current Grade: ${student.grade || 'N/A'}`);
  lines.push(`Date Generated: ${new Date().toLocaleDateString()}`);
  lines.push('');

  for (const year of transcript) {
    lines.push(`${year.academicYear} — Grade ${year.grade} Section ${year.section} (${year.source === 'historical' ? 'Historical Record' : 'Current System'})`);
    lines.push('-'.repeat(50));

    if (year.subjects && year.subjects.length > 0) {
      for (const subj of year.subjects) {
        if (subj.marks && subj.marks.length > 0) {
          for (const m of subj.marks) {
            const pct = percentage(m.mark ?? m.marksObtained, m.maxMark ?? m.maxMarks);
            lines.push(`  ${subj.subject} (${subj.subjectCode || ''}): ${m.mark ?? m.marksObtained}/${m.maxMark ?? m.maxMarks} (${m.term || 'Annual'}) ${pct !== null ? `= ${pct}%` : ''}`);
          }
        } else if (subj.mark !== undefined) {
          const pct = percentage(subj.mark, subj.maxMark);
          lines.push(`  ${subj.subject}: ${subj.mark}/${subj.maxMark} ${pct !== null ? `= ${pct}%` : ''}`);
        }
      }
    }

    if (year.average !== null) {
      lines.push(`  Average: ${year.average}%`);
    }
    if (year.totalObtained !== null && year.totalMax !== null) {
      lines.push(`  Total: ${year.totalObtained}/${year.totalMax}`);
    }
    if (year.schoolInfo) {
      lines.push(`  School: ${year.schoolInfo}`);
    }
    if (year.notes) {
      lines.push(`  Notes: ${year.notes}`);
    }
    lines.push('');
  }

  lines.push('='.repeat(50));
  lines.push('End of Transcript');
  lines.push('This is an official document generated by the Student Management System.');

  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `transcript-${student.name.replace(/\s+/g, '-')}-${Date.now()}.txt`;
  link.click();
}

export function StudentTranscriptPage() {
  const { user } = useAuth();
  const { data, loading, error, run } = useAsync(getTranscriptRequest);

  useRecordEvents({ userId: user?.id, onEvent: () => run() });

  if (loading && !data) return <Spinner label="Generating transcript…" />;
  if (error && !data) return <ErrorState message={extractErrorMessage(error, 'Could not generate transcript')} onRetry={run} />;

  const student = data?.student;
  const transcript = data?.transcript ?? [];

  const gradeSortKey = (grade) => {
    const order = { 9: 1, 10: 2, 11: 3, 12: 4 };
    return order[grade] ?? 99;
  };

  const sortedTranscript = [...transcript].sort((a, b) => {
    const yearDiff = (a.academicYear || '').localeCompare(b.academicYear || '');
    if (yearDiff !== 0) return yearDiff;
    return gradeSortKey(a.grade) - gradeSortKey(b.grade);
  });

  return (
    <div className="max-w-3xl mx-auto">
      <PageHeader
        title="Official Transcript"
        subtitle={student ? `Complete academic record for ${student.name}` : 'No transcript data available'}
        actions={
          <div className="flex gap-2">
            <Button variant="secondary" onClick={printTranscript}>
              <Printer size={15} aria-hidden="true" /> Print
            </Button>
            <Button variant="secondary" onClick={() => downloadTranscript(student, sortedTranscript)}>
              <Download size={15} aria-hidden="true" /> Download
            </Button>
          </div>
        }
      />

      {error && !data && <ErrorState message={extractErrorMessage(error, 'Could not load transcript')} onRetry={run} />}

      {!student && <EmptyState icon={<FileText size={28} aria-hidden="true" />} title="No transcript available" description="Your academic records will appear here once you have grades or historical records." />}

      {student && (
        <div className="space-y-6" id="transcript-content">
          <div className="panel p-6 print:hidden">
            <div className="text-center mb-6">
              <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-primary-100 dark:bg-primary-900/30 mb-4">
                <Award size={32} className="text-primary-600 dark:text-primary-400" aria-hidden="true" />
              </div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Official Academic Transcript</h1>
              <p className="text-slate-500 dark:text-slate-400 mt-1">Student Management System</p>
            </div>

            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="font-medium text-slate-500 dark:text-slate-400">Student Name</p>
                <p className="font-semibold">{student.name}</p>
              </div>
              <div>
                <p className="font-medium text-slate-500 dark:text-slate-400">National ID</p>
                <p className="font-semibold">{student.nationalId || 'N/A'}</p>
              </div>
              <div>
                <p className="font-medium text-slate-500 dark:text-slate-400">Roll Number</p>
                <p className="font-semibold">{student.rollNumber || 'N/A'}</p>
              </div>
              <div>
                <p className="font-medium text-slate-500 dark:text-slate-400">Current Grade</p>
                <p className="font-semibold">{student.grade ? `Grade ${student.grade}` : 'N/A'}</p>
              </div>
              <div className="col-span-2">
                <p className="font-medium text-slate-500 dark:text-slate-400">Date Generated</p>
                <p className="font-semibold">{new Date().toLocaleDateString()}</p>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            {sortedTranscript.length === 0 ? (
              <EmptyState icon={<FileText size={28} aria-hidden="true" />} title="No academic records" description="No records found for this student." />
            ) : (
              sortedTranscript.map((year, idx) => (
                <div key={idx} className="panel">
                  <div className="panel__header flex flex-wrap items-center justify-between gap-2">
                    <div className="flex items-center gap-3">
                      <GradeBadge grade={year.grade} source={year.source} />
                      <span className="font-medium text-slate-700 dark:text-slate-300">{year.academicYear}</span>
                      <span className="text-sm text-slate-500 dark:text-slate-400">Section {year.section}</span>
                      {year.className && <span className="text-sm text-slate-500 dark:text-slate-400">({year.className})</span>}
                      {year.average !== null && <Badge tone={year.average >= 50 ? 'success' : 'danger'}>{year.average}%</Badge>}
                    </div>
                    {year.schoolInfo && <span className="text-sm text-slate-500 dark:text-slate-400">School: {year.schoolInfo}</span>}
                  </div>

                  <div className="overflow-x-auto">
                    <table className="table w-full text-[13px]">
                      <thead>
                        <tr>
                          <th className="th">Subject</th>
                          <th className="th">Term</th>
                          <th className="th">Marks</th>
                          <th className="th">Out of</th>
                          <th className="th">Result</th>
                        </tr>
                      </thead>
                      <tbody>
                        {(year.subjects || []).map((subj, si) => {
                          if (subj.marks && subj.marks.length > 0) {
                            return subj.marks.map((m, mi) => (
                              <tr key={`${si}-${mi}`} className="transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/60">
                                <td className="td font-medium">{mi === 0 ? subj.subject : ''}</td>
                                <td className="td">{m.term || 'Annual'}</td>
                                <td className="td font-semibold">{m.mark ?? m.marksObtained}</td>
                                <td className="td text-slate-500 dark:text-slate-400">{m.maxMark ?? m.maxMarks}</td>
                                <td className="td">
                                  {(() => {
                                    const pct = percentage(m.mark ?? m.marksObtained, m.maxMark ?? m.maxMarks);
                                    return pct == null ? <Badge tone="neutral">—</Badge> : <Badge tone={pct >= 50 ? 'success' : 'danger'}>{pct}%</Badge>;
                                  })()}
                                </td>
                              </tr>
                            ));
                          }
                          if (subj.mark !== undefined) {
                            return (
                              <tr key={si} className="transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/60">
                                <td className="td font-medium">{subj.subject}</td>
                                <td className="td">Annual</td>
                                <td className="td font-semibold">{subj.mark}</td>
                                <td className="td text-slate-500 dark:text-slate-400">{subj.maxMark}</td>
                                <td className="td">
                                  {(() => {
                                    const pct = percentage(subj.mark, subj.maxMark);
                                    return pct == null ? <Badge tone="neutral">—</Badge> : <Badge tone={pct >= 50 ? 'success' : 'danger'}>{pct}%</Badge>;
                                  })()}
                                </td>
                              </tr>
                            );
                          }
                          return null;
                        })}
                      </tbody>
                    </table>
                  </div>

                  {year.notes && (
                    <div className="pt-4 border-t border-slate-200 dark:border-slate-700 text-sm text-slate-500 dark:text-slate-400">
                      <span className="font-medium">Notes:</span> {year.notes}
                    </div>
                  )}
                </div>
              ))
            )}

            <div className="panel p-6 print:hidden text-center border-t-2 border-slate-200 dark:border-slate-700">
              <p className="text-slate-500 dark:text-slate-400">
                This transcript includes both historical records (imported from previous school records) and current system records.
                Historical records are marked with an amber badge; current system records with a green badge.
              </p>
              <p className="text-sm text-slate-400 dark:text-slate-500 mt-2">
                Generated on {new Date().toLocaleString()} · Student Management System
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}